 '(agda2-highlight-bound-variable-face          ((t (:foreground "purple"))))
 '(agda2-highlight-coinductive-constructor-face ((t (:foreground "firebrick3"))))
 '(agda2-highlight-error-face                   ((t (:foreground "red" :underline t))))
 '(agda2-highlight-field-face                   ((t (:foreground "deeppink"))))
 '(agda2-highlight-function-face                ((t (:foreground "darkgreen"))))
 '(agda2-highlight-inductive-constructor-face   ((t (:foreground "firebrick3"))))
 '(agda2-highlight-keyword-face                 ((t (:weight bold))))
 '(agda2-highlight-module-face                  ((t (:foreground "medium blue"))))
 '(agda2-highlight-postulate-face               ((t (:foreground "darkgreen"))))
 '(agda2-highlight-unsolved-constraint-face     ((t (:background "yellow"))))
 '(agda2-highlight-unsolved-meta-face           ((t (:background "yellow"))))
 '(font-lock-comment-face                       ((((class color) (min-colors 88) (background light)) (:foreground "DarkSlateGray"))))
